name: Contracts Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm i
      working-directory: contracts
    - name: Run tests
      run: npx buidler test
      working-directory: contracts
